const {test}=require('node:test'),assert=require('node:assert/strict');
require('../wbgt_core.js');require('../galazo_weatherpro.js');require('../galazo_core.js');
const src=GalazoWeatherPro,core=GalazoCore,H=src.HOUR;
const now=Date.parse('2026-10-02T08:00Z'),range=src.windowFor('2026-10-02',7,now);
const settings=Object.fromEntries(core.CRITERIA.map(c=>[c.key,c.defaultValue]));
const h={issuedInstant:'2026-07-02T00:00:00Z',issuedInterval:'2026-07-02T00:00:00Z',iso:'2026-07-02T11:00Z',endIso:'2026-07-02T12:00Z',t:'2026-07-02T13:00',date:'2026-07-02',offset:'UTC+2',tt:30,rh:60,wind2:2,solar:700,ppp:1013.25,ffg:30,rr:0,thunder:0,visibility:20000};
const ctx={lat:51.9225,lon:4.4792,elevation:0};
function records(ms,period){const a={validFrom:new Date(ms).toISOString(),validUntil:new Date(ms+(period==='PT1H'?H:0)).toISOString(),issuedAt:'2026-10-01T21:43:00.000Z',validPeriod:period};const spec=period==='PT1H'?src.INTERVAL:src.INSTANT;for(const [key,[field]] of Object.entries(spec))a[field]=({tt:20,td:15,rh:70,ff:10,wind2:2,dd:180,n:4,apparent:19,visibility:20000,uv:3,ppp:1013,ww:4,ffg:20,rr:0,pop:0,thunder:0,sun:30,solar:400})[key];return a;}
test('Seven calendar days, capped at day 7, never invent later forecast days',()=>{assert.equal((range.until-range.from)/H,168);assert.equal(range.start,'2026-10-02');assert.equal(range.end,'2026-10-09');assert.equal(src.windowFor('2026-10-08',7,now).end,'2026-10-09');for(const [d,n] of [['2026-10-01',7],['2026-10-09',1],['2026-10-02',8],['2026-10-02',0]])assert.throws(()=>src.windowFor(d,n,now));});
test('DST: 25/23 hour days preserve repeated/missing local hours using UTC instants',()=>{
 for(const [d,dateNow,count] of [['2026-10-25','2026-10-25T10:00Z',25],['2026-03-29','2026-03-29T10:00Z',23]]){
  const w=src.windowFor(d,1,Date.parse(dateNow)),out=src.normalize([],[],w);assert.equal(out.hours.length,count);assert.equal(new Set(out.hours.map(h=>h.iso)).size,count);
  if(count===25){const repeated=out.hours.filter(h=>h.t.endsWith('T02:00'));assert.equal(repeated.length,2);assert.notEqual(repeated[0].offset,repeated[1].offset);}
 }
});
test('Hourly end timestamps match their preceding interval regardless of textual offset',()=>{const ms=range.from,iv=records(ms,'PT1H'),inst=records(ms+H,'PT0S');inst.validFrom='2026-10-02T01:00:00+02:00';inst.validUntil=inst.validFrom;const out=src.normalize([inst],[iv],{...range,until:ms+H});assert.equal(out.hours[0].tt,20);assert.equal(out.hours[0].rr,0);assert.equal(out.hours[0].t,'2026-10-02T00:00');});
test('Null, empty, invalid and missing values stay missing; no wind or gust defaults',()=>{const ms=range.from,iv=records(ms,'PT1H'),inst=records(ms+H,'PT0S');delete iv.maxWindGustInKilometerPerHour;iv.precipitationAmountInMillimeter='';inst.windSpeedInKilometerPerHour=null;inst.relativeHumidityInPercent=101;const out=src.normalize([inst],[iv],{...range,until:ms+2*H});for(const k of ['ff','ffg','rr','rh'])assert.equal(out.hours[0][k],null);assert.equal(out.hours[1].available,false);assert.equal(out.hours[1].ww,null);assert.ok(out.diagnostics.some(x=>x.code==='invalid-field'));});
test('Each hour has its own physical WBGT; formula follows the attached GGD document',()=>{const a=core.calculateHour(h,ctx),b=core.calculateHour({...h,tt:35,rh:80},ctx),c=core.calculateHour({...h,solar:0},ctx);assert.ok(a.value>20&&a.value<40);assert.ok(b.value>a.value);assert.ok(c.value<a.value);assert.equal(a.value,.7*a.components.Tnw+.2*a.components.Tg+.1*a.components.Ta);assert.notEqual(a.components.Tnw,a.components.Tw);});
test('Missing WBGT input, missing site altitude, inconsistent runs and invalid inputs produce no WBGT',()=>{for(const key of ['tt','rh','wind2','solar','ppp']){const c=core.calculateHour({...h,[key]:null},ctx);assert.equal(c.value,null);assert.ok(c.reason);}assert.equal(core.calculateHour(h,{...ctx,elevation:null}).value,null);assert.equal(core.calculateHour({...h,issuedInstant:null},ctx).value,null);assert.ok(core.calculateHour({...h,issuedInterval:'2026-07-02T02:00:00+02:00'},ctx).value!==null);assert.equal(core.calculateHour({...h,issuedInstant:'2026-10-01T00:00Z',issuedInterval:'2026-10-02T00:00Z'},ctx).value,null);for(const change of [{tt:100},{rh:101},{wind2:-1},{solar:-1},{ppp:0}])assert.equal(core.calculateHour({...h,...change},ctx).value,null);assert.equal(core.calculateHour({...h,iso:'2026-07-02T23:00Z',solar:500},ctx).value,null);});
test('Warnings are one combined item per day; absent values never trigger warnings',()=>{const rows=Array.from({length:24},(_,i)=>({...h,iso:new Date(Date.parse(h.iso)+i*H).toISOString(),wbgt:28,ffg:60,rr:6,thunder:40,visibility:500}));const w=core.dailyWarnings(rows,{...settings,wbgt:25});assert.equal(w.length,1);assert.equal(w[0].triggers.length,6);assert.equal(w[0].triggers[0].hours.length,24);assert.equal(core.dailyWarnings([{...h,wbgt:null,tt:null,ffg:null,rr:null,thunder:null,visibility:null}],settings).length,0);assert.equal(core.dailyWarnings([{...h,tt:20,wbgt:35}],settings).length,0,'no implicit WBGT medical threshold');assert.throws(()=>core.dailyWarnings(rows,{...settings,thunder:101}));});
test('Process rejects any other weather source',()=>assert.throws(()=>core.process({source:'HARMONIE',hours:[],diagnostics:[]},ctx,settings),/uitsluitend WeatherPro/));
test('Adapter only calls WeatherPro, tolerates one failed period, rejects empty responses',async()=>{
 const old=global.fetch,calls=[];global.fetch=async(url,options)=>{calls.push(String(url));if(String(url).includes('/token/'))return {ok:true,text:async()=> 'test-only-token-value'};const u=new URL(url);if(u.searchParams.get('validPeriod')==='PT1H')return {ok:false,status:503};return {ok:true,json:async()=>({forecasts:[records(range.from+H,'PT0S')]})};};
 try{const out=await src.fetch(ctx.lat,ctx.lon,{...range,until:range.from+H});assert.equal(out.hours[0].ffg,null);assert.ok(out.diagnostics.some(d=>d.code==='request-failed'));assert.equal(calls.length,3);assert.ok(calls.every(u=>new URL(u).hostname==='api.weatherpro.com'||new URL(u).hostname==='point-forecast-weatherpro.meteogroup.com'));global.fetch=async url=>String(url).includes('/token/')?{ok:true,text:async()=> 'test-only-token-value'}:{ok:true,json:async()=>({forecasts:[]})};await assert.rejects(()=>src.fetch(ctx.lat,ctx.lon,range),/geen uren/);}finally{global.fetch=old;}
});
