import fs from 'node:fs';
import {createWeatherIcon,WEATHER_ICON_LABELS,WEATHER_ICON_BASICS,WEATHER_ICON_SPECS} from '../editor-src/weather-icons.js';
import {parseCommand} from '../editor-src/regio-voice.js';
let id=0;
const React={useId:()=>`print${++id}`,createElement:(type,props,...children)=>({type,props:props||{},children})};
const icon=createWeatherIcon(React);
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
function render(n){if(n==null||n===false)return '';if(Array.isArray(n))return n.map(render).join('');if(typeof n!=='object')return escape(n);return `<${n.type}${Object.entries(n.props).filter(([k])=>k!=='key').map(([k,v])=>` ${k.replace(/[A-Z]/g,x=>'-'+x.toLowerCase())}="${escape(v)}"`).join('')}>${n.children.map(render).join('')}</${n.type}>`;}
const basicAliases={zon:'zon / zonnig',sluierbewolking:'zon met sluierbewolking',zon_achter_wolk:'half bewolkt',bewolkt:'bewolkt / wolk',zon_wolk_regen:'bui / buien',regen:'regen',onweer:'onweer',mist3:'mist',sneeuw:'sneeuw'};
function card(type,label,spoken=label){for(const phrase of spoken.split(' / ')){if(parseCommand(phrase)?.type!==type && JSON.stringify(WEATHER_ICON_SPECS[parseCommand(phrase)?.type])!==JSON.stringify(WEATHER_ICON_SPECS[type]))throw Error(`Unrecognized printed phrase: ${phrase}`);}return `<article><svg viewBox="0 0 96 96" aria-label="${escape(label)}">${render(icon({type,s:96}))}</svg><div><strong>${escape(label)}</strong><span>Zeg: “${escape(spoken)}”</span></div></article>`;}
const basics=new Set(WEATHER_ICON_BASICS.map(([t])=>t));
const html=`<!doctype html><html lang="nl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Spraakkaart regiokaart · Weerlab</title><style>
*{box-sizing:border-box}body{font:14px/1.45 system-ui,sans-serif;color:#172b44;margin:0;background:#e8edf3}main{max-width:1000px;margin:24px auto;background:white;padding:32px}h1{font-size:28px;margin:0}h2{font-size:20px;margin:24px 0 12px}.intro{max-width:780px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}article{display:flex;align-items:center;border:1px solid #ccd7e4;border-radius:8px;padding:6px;break-inside:avoid;min-height:78px}article svg{width:64px;height:64px;flex-shrink:0;margin-right:12px}strong,span{display:block}span{font-size:12px;color:#3d5269}.pdf-download{float:right;margin-left:10px;padding:12px 18px;border-radius:8px;background:#172b44;color:white;text-decoration:none}button{padding:12px 18px;background:#087f8c;color:white;border:0;border-radius:8px;font:inherit;cursor:pointer;float:right}.examples{display:grid;grid-template-columns:1fr 1fr;gap:8px}.examples p{margin:0;padding:10px;background:#f0f7fc}.eyebrow{font-weight:700;letter-spacing:2px;font-size:11px;color:#087f8c}@page{size:A4;margin:12mm}@media print{body{background:white;font-size:10pt}main{padding:0;margin:0;max-width:none}button,.pdf-download{display:none}h1{font-size:22pt}h2{font-size:15pt}article{min-height:16mm;padding:3px}article svg{width:12mm;height:12mm}span{font-size:9pt}.more{break-before:page}.grid{gap:1.5mm}h2{break-after:avoid;margin:14px 0 8px}.examples p{padding:7px}}@media(max-width:620px){main{margin:0;padding:16px}.grid,.examples{grid-template-columns:1fr}}
</style><main><a class="pdf-download" href="./regiokaart-spraakkaart.pdf" download>PDF downloaden</a><button onclick="window.print()">Pagina afdrukken</button><p class="eyebrow">WEERLAB · KAARTENSTUDIO</p><h1>Spraakkaart regiokaart</h1><p class="intro">Klik in de editor op <b>Microfoon aan</b>. Spreek één opdracht tegelijk en wacht tot die is klaargezet. Elk onderdeel verschijnt op een vaste klaarzetplek op de kaart. Sleep het daarna zelf naar de juiste plek. Met <b>Stop luisteren</b> zet je de microfoon uit.</p><h2>Veelgebruikte weersymbolen</h2><div class="grid">${WEATHER_ICON_BASICS.map(([type])=>card(type,WEATHER_ICON_LABELS[type],basicAliases[type]||WEATHER_ICON_LABELS[type])).join('')}</div><h2>Temperaturen, dagen en plaatsen</h2><div class="examples"><p><b>Temperatuur</b><br>“16 graden” → 16°<br>“twintig graden” → 20°<br>“min drie graden” → −3°</p><p><b>Dag</b><br>“maandag”, “dinsdag”, “woensdag”, “donderdag”, “vrijdag”, “zaterdag” of “zondag”</p><p><b>Plaatsnaam</b><br>“Rotterdam”, “Dordrecht”, “Gouda” of een plaats uit de regiolijst.<br>Andere plaats: “plaats” + de naam.</p><p><b>Corrigeren</b><br>Gebruik Ongedaan maken en spreek opnieuw, of typ de opdracht bij “Voorbeelden en tekstinvoer”.</p></div><section class="more"><h2>Alle overige symbolen en varianten</h2><p>Zeg de naam onder het symbool. Dit zijn de bestaande symbolen uit de editor.</p><div class="grid">${Object.entries(WEATHER_ICON_LABELS).filter(([type])=>!basics.has(type)).map(([type,label])=>card(type,label)).join('')}</div></section></main></html>`;
fs.writeFileSync(new URL('../regiokaart-spraakkaart.html',import.meta.url),html);
console.log(`Print card: ${Object.keys(WEATHER_ICON_LABELS).length} existing symbols; every printed command verified.`);
